
theme: jekyll-theme-cayman

title: DiSCo - Data Science Community @ Ben Gurion University, Beersheva, Israel
description: Learn, Practice, Teamup, Compete and Have Fun...! 

url: "http://localhost:3000"

# Google Analytics
google_analytics: UA-116195310-1
